/****************************************************************************
Copyright (c) [2012 - 2017] Texas Instruments Incorporated

All rights reserved not granted herein.

Limited License.

 Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
 license under copyrights and patents it now or hereafter owns or controls to
 make,  have made, use, import, offer to sell and sell ('Utilize') this software
 subject to the terms herein.  With respect to the foregoing patent license,
 such license is granted  solely to the extent that any such patent is necessary
 to Utilize the software alone.  The patent license shall not apply to any
 combinations which include this software, other than combinations with devices
 manufactured by or for TI ('TI Devices').  No hardware patent is licensed
 hereunder.

 Redistributions must preserve existing copyright notices and reproduce this
 license (including the above copyright notice and the disclaimer and
 (if applicable) source code license limitations below) in the documentation
 and/or other materials provided with the distribution

 Redistribution and use in binary form, without modification, are permitted
 provided that the following conditions are met:

 * No reverse engineering, decompilation, or disassembly of this software
   is permitted with respect to any software provided in binary form.

 * Any redistribution and use are licensed by TI for use only with TI Devices.

 * Nothing shall obligate TI to provide you with source code for the software
   licensed and provided to you in object code.

 If software source code is provided to you, modification and redistribution of
 the source code are permitted provided that the following conditions are met:

 * Any redistribution and use of the source code, including any resulting
   derivative works, are licensed by TI for use only with TI Devices.

 * Any redistribution and use of any object code compiled from the source code
   and any resulting derivative works, are licensed by TI for use only with TI
   Devices.

 Neither the name of Texas Instruments Incorporated nor the names of its
 suppliers may be used to endorse or promote products derived from this software
 without specific prior written permission.

 DISCLAIMER.

 THIS SOFTWARE IS PROVIDED BY TI AND TI’S LICENSORS 'AS IS' AND ANY EXPRESS OR
 IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 IN NO EVENT SHALL TI AND TI’S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
******************************************************************************
*/
/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _CHAINS_HAL_MATCH_TEMPLATE_H_
#define _CHAINS_HAL_MATCH_TEMPLATE_H_

#include <include/link_api/system.h>
#include <include/alglink_api/algorithmLink_matchTemplate.h>
#include <include/link_api/ipcLink.h>
#include "hal_match_template.h"

#define MAX_MT_CORE_COUNT      (2U)
#define MAX_MT_INSTANCE_COUNT  (1U)

typedef struct {
    UInt32 NullSrcIPCOut_A15_DSP_LinkID[HAL_MT_PROC_ID_MAX];
    UInt32 IPCIn_DSP_A15_LinkID[HAL_MT_PROC_ID_MAX];
    UInt32 Alg_MatchTemplate_LinkID[HAL_MT_PROC_ID_MAX];
    UInt32 IPCOut_DSP_A15_LinkID[HAL_MT_PROC_ID_MAX];
    UInt32 IPCInNull_A15_DSP_LinkID[HAL_MT_PROC_ID_MAX];

    IpcLink_CreateParams                    NullSrcIPCOut_A15_DSP_Prm[HAL_MT_PROC_ID_MAX];
    IpcLink_CreateParams                    IPCIn_DSP_A15_Prm[HAL_MT_PROC_ID_MAX];
    AlgorithmLink_MatchTemplateCreateParams Alg_MatchTemplate_Prm[HAL_MT_PROC_ID_MAX];
    IpcLink_CreateParams                    IPCOut_DSP_A15_Prm[HAL_MT_PROC_ID_MAX];
    IpcLink_CreateParams                    IPCInNull_A15_DSP_Prm[HAL_MT_PROC_ID_MAX];
} chains_hal_match_templateObj;

Void chains_hal_match_template_SetLinkId(unsigned int procID, chains_hal_match_templateObj *pObj);

Void chains_hal_match_template_ResetLinkPrms(unsigned int procID, chains_hal_match_templateObj *pObj);

Void chains_hal_match_template_SetPrms(unsigned int procID, chains_hal_match_templateObj *pObj);

Void chains_hal_match_template_ConnectLinks(unsigned int procID, chains_hal_match_templateObj *pObj);

Int32 chains_hal_match_template_Create(unsigned int procID, chains_hal_match_templateObj *pObj, Void *appObj);

Int32 chains_hal_match_template_Start(unsigned int procID, chains_hal_match_templateObj *pObj);

Int32 chains_hal_match_template_Stop(unsigned int procID, chains_hal_match_templateObj *pObj);

Int32 chains_hal_match_template_Delete(unsigned int procID, chains_hal_match_templateObj *pObj);

Void chains_hal_match_template_printBufferStatistics(unsigned int procID, chains_hal_match_templateObj *pObj);

Void chains_hal_match_template_printStatistics(unsigned int procID, chains_hal_match_templateObj *pObj);

Void chains_hal_match_template_SetAppPrms(unsigned int procID, chains_hal_match_templateObj *pObj, Void *appObj);

#endif /* _CHAINS_HAL_MATCH_TEMPLATE_H_ */
