/******************************************************************************
Copyright (c) [2012 - 2017] Texas Instruments Incorporated

All rights reserved not granted herein.

Limited License.

 Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
 license under copyrights and patents it now or hereafter owns or controls to
 make,  have made, use, import, offer to sell and sell ("Utilize") this software
 subject to the terms herein.  With respect to the foregoing patent license,
 such license is granted  solely to the extent that any such patent is necessary
 to Utilize the software alone.  The patent license shall not apply to any
 combinations which include this software, other than combinations with devices
 manufactured by or for TI ("TI Devices").  No hardware patent is licensed
 hereunder.

 Redistributions must preserve existing copyright notices and reproduce this
 license (including the above copyright notice and the disclaimer and
 (if applicable) source code license limitations below) in the documentation
 and/or other materials provided with the distribution

 Redistribution and use in binary form, without modification, are permitted
 provided that the following conditions are met:

 * No reverse engineering, decompilation, or disassembly of this software
   is permitted with respect to any software provided in binary form.

 * Any redistribution and use are licensed by TI for use only with TI Devices.

 * Nothing shall obligate TI to provide you with source code for the software
   licensed and provided to you in object code.

 If software source code is provided to you, modification and redistribution of
 the source code are permitted provided that the following conditions are met:

 * Any redistribution and use of the source code, including any resulting
   derivative works, are licensed by TI for use only with TI Devices.

 * Any redistribution and use of any object code compiled from the source code
   and any resulting derivative works, are licensed by TI for use only with TI
   Devices.

 Neither the name of Texas Instruments Incorporated nor the names of its
 suppliers may be used to endorse or promote products derived from this software
 without specific prior written permission.

 DISCLAIMER.

 THIS SOFTWARE IS PROVIDED BY TI AND TI�S LICENSORS "AS IS" AND ANY EXPRESS OR
 IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 IN NO EVENT SHALL TI AND TI�S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
******************************************************************************/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef __CHAINS_HAL_SINGLE_CAMERA_SAVE_LOCAL_PRIV_H__
#define __CHAINS_HAL_SINGLE_CAMERA_SAVE_LOCAL_PRIV_H__

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/vpeLink.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/nullLink.h>

typedef struct {
    UInt32    CaptureLinkID;
    //UInt32    Dup_single_LinkID;
    //UInt32    VPE_single_0_LinkID;
    UInt32    VPELinkID;
    UInt32    IPCOut_IPU1_0_A15_0_0LinkID;
    UInt32    IPCIn_A15_0_IPU1_0_0LinkID;
    UInt32    NullLinkID;

    CaptureLink_CreateParams                CapturePrm;
    //DupLink_CreateParams                    Dup_single_Prm;
    //VpeLink_CreateParams                    VPE_single_0_Prm;
    VpeLink_CreateParams                    VPEPrm;
    IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_0Prm;
    IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_0Prm;
    NullLink_CreateParams                   NullPrm;
} chains_hal_single_camera_save_localObj;

Void chains_hal_single_camera_save_local_SetLinkId(chains_hal_single_camera_save_localObj *pObj);

Void chains_hal_single_camera_save_local_ResetLinkPrms(chains_hal_single_camera_save_localObj *pObj);

Void chains_hal_single_camera_save_local_SetPrms(chains_hal_single_camera_save_localObj *pObj);

Void chains_hal_single_camera_save_local_ConnectLinks(chains_hal_single_camera_save_localObj *pObj);

Int32 chains_hal_single_camera_save_local_Create(chains_hal_single_camera_save_localObj *pObj, Void *appObj);

Int32 chains_hal_single_camera_save_local_Start(chains_hal_single_camera_save_localObj *pObj);

Int32 chains_hal_single_camera_save_local_Stop(chains_hal_single_camera_save_localObj *pObj);

Int32 chains_hal_single_camera_save_local_Delete(chains_hal_single_camera_save_localObj *pObj);

Void chains_hal_single_camera_save_local_printBufferStatistics(chains_hal_single_camera_save_localObj *pObj);

Void chains_hal_single_camera_save_local_printStatistics(chains_hal_single_camera_save_localObj *pObj);

Void chains_hal_single_camera_save_local_SetAppPrms(chains_hal_single_camera_save_localObj *pObj, Void *appObj);
Void hal_single_camera_null_link_callback(System_LinkChInfo *pChInfo, Void *pBuf, Void *arg);

#endif /* __CHAINS_HAL_SINGLE_CAMERA_SAVE_LOCAL_PRIV_H__ */
